<?php

function delete_all_menu($maycache) {
  $items = array();

  $items[] = array(
    'path'               => 'admin/content/delete_content',
    'title'              => t('Delete all content'),
    'description'        => t('Delete all nodes and comments on this site. This is useful for development sites, or prior to launching the site. Otherwise it destroys all data on a site.'),
    'callback'           => 'drupal_get_form',
    'callback arguments' => array('delete_all_content'),
    'access'             => user_access('administer content'),
    'type'               => MENU_NORMAL_ITEM);

  $items[] = array(
    'path'               => 'admin/user/delete_users',
    'title'              => t('Delete all users'),
    'description'        => t('Delete all users on this site. This is useful for development sites, or prior to launching the site. Otherwise it destroys all data on a site.'),
    'callback'           => 'drupal_get_form',
    'callback arguments' => array('delete_all_users'),
    'access'             => user_access('administer users'),
    'type'               => MENU_NORMAL_ITEM);

  return $items;
}

function delete_all_content() {
  $form['action'] = array(
    '#type'  => 'hidden',
    '#value' => 'content',
  );
  return confirm_form(
    $form,
    t('Are you sure you want to delete all content?'),
    'admin',
    '',
    t('Delete'),
    t('Cancel'),
    'delete_all_content');
}

function delete_all_content_submit() {
  $result = db_query('SELECT nid FROM {node}');

  $count = 0;
  while($data = db_fetch_object($result)) {
    node_delete($data->nid);
    db_query("DELETE FROM {url_alias} WHERE src LIKE 'node/%d%%'", $data->nid);
    $count++;
  }

  db_query("UPDATE {sequences} SET id = 1 WHERE name = 'node_nid'");
  db_query("UPDATE {sequences} SET id = 1 WHERE name = 'comment_cid'");

  drupal_set_message(t('All nodes and comments have been deleted. Number of nodes deleted: !count.', array('!count' => $count)));

  drupal_goto('admin');
}

function delete_all_users() {
  $form['action'] = array(
    '#type'  => 'hidden',
    '#value' => 'users',
  );
  return confirm_form(
    $form,
    t('Are you sure you want to delete all users?'),
    'admin',
    '',
    t('Delete'),
    t('Cancel'),
    'delete_all_content');
}

function delete_all_users_submit() {
  $result = db_query('SELECT uid FROM {users} WHERE uid > 1');

  $count = 0;
  while($data = db_fetch_object($result)) {
    user_delete(array(), $data->uid);
    $count++;
  }

  db_query("UPDATE {sequences} SET id = 1 WHERE name = 'users_uid'");

  drupal_set_message(t('All users have been deleted. Number of users deleted: !count.', array('!count' => $count)));

  drupal_goto('admin');
}
